POST http://localhost:8080/JMS_Project1B-1.0-SNAPSHOT/api/users
Content-Type: application/json
Accept: application/json

{
  "userName": "Jacek"
}

#####

GET http://localhost:8080/JMS_Project1B-1.0-SNAPSHOT/api/users/Jacek
Content-Type: application/json
Accept: application/json

#####

POST http://localhost:8080/JMS_Project1B-1.0-SNAPSHOT/api/channels/publicChannel
Content-Type: application/json
Accept: application/json

{
  "channelName": "Gdańsk"
}

##### create a private channel indicating allowed users

POST http://localhost:8080/JMS_Project1B-1.0-SNAPSHOT/api/channels/privateChannel
Content-Type: application/json
Accept: application/json

{
  "channelName": "Testowy",
  "isPrivate": true,
  "permittedUsers": ["Jacek", "Marek", "Krzysiek"]
}

##### get list of all public channels

GET http://localhost:8080/JMS_Project1B-1.0-SNAPSHOT/api/channels

##### get history from channel, check if permitted to view;

GET http://localhost:8080/JMS_Project1B-1.0-SNAPSHOT/api/channels/history/Testowy/Jacek