POST http://localhost:8080/JMS_Project1B-1.0-SNAPSHOT/api/users
Content-Type: application/json
Accept: application/json

{
  "userName": "Jacek"
}

#####

GET http://localhost:8080/JMS_Project1B-1.0-SNAPSHOT/api/users/Jacek
Content-Type: application/json
Accept: application/json

#####

POST http://localhost:8080/JMS_Project1B-1.0-SNAPSHOT/api/channels/publicChannel
Content-Type: application/json
Accept: application/json

{
  "channelName": "Ogólny"
}

#####

POST http://localhost:8080/JMS_Project1B-1.0-SNAPSHOT/api/channels/privateChannel
Content-Type: application/json
Accept: application/json

{
  "channelName": "Magiczny",
  "isPrivate": true,
  "permittedUsers": ["Jacek", "Marek"]
}

#####

GET http://localhost:8080/JMS_Project1B-1.0-SNAPSHOT/api/channels

#####

GET http://localhost:8080/JMS_Project1B-1.0-SNAPSHOT/api/channels/history/Ogólny
